---
title: "Final"
author: "Jianing Liu"
date: "2023-11-29"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)
library(readxl)
library(lubridate)
library(leaflet)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 16, 
  fig.height = 12,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r load the data files}
map <-
  read_csv("data/HydroWASTE_v10.csv")

wwtp <-
  read_csv("data/SARS-CoV-2_concentrations_measured_in_NYC_Wastewater_20231129.csv")
```


```{r clean the mapping data file and rename plant names}
map_new <-
  map |>
  janitor::clean_names() |>
  select(waste_id, wwtp_name, lat_wwtp, lon_wwtp) |>
  mutate(wrrf_abbreviation = recode( wwtp_name,
    "New York C   Rockaway WPCP" = "RK",
    "New York C   Red Hook WPCP" = "RH",
    "New York C   Port Richmond WPCP" = "PR",
    "New York C   Oakwood Beach WPCP" = "OB",
    "New York C   26th Ward WPCP" = "26W",
    "New York C   Tallman Island WPCP" = "TI",
    "New York C   North River WPCP" = "NR",
    "New York C   Coney Island WPCP" = "CI",
    "New York C   Jamaica WPCP" = "JA",
    "New York C   Hunts Point WPCP" = "HP",
    "New York C   Owls Head WPCP" = "OH",
    "New York C   Bowery Bay WPCP" = "BB",
    "New York C   Newtown Creek WPCP" = "NC",
    "New York C   Wards Island WPCP" = "WI",
  ))
```

```{r clean the waste water data file}
wwtp_cleaned <-
  wwtp |>
  janitor:: clean_names()
```

```{r merge the waste water data file and mapping data file}
merge_df <- inner_join(map_new, wwtp_cleaned, by = "wrrf_abbreviation")
```

```{r choose the variables from the merged data file}
nyc_wwtp <-
  merge_df |>
  rename(concentration = concentration_sars_co_v_2_gene_target_n1_copies_l) |>
  drop_na(concentration) |>
  separate(sample_date, into = c("month", "day", "year"), convert = TRUE) %>% 
   mutate(
     year = as.character(year),
     month = factor(month, levels = 1:12),
     month = recode(month,
                        "1" = "January",
                        "2" = "February",
                        "3" = "March",
                        "4" = "April",
                        "5" = "May",
                        "6" = "June",
                        "7" = "July",
                        "8" = "August",
                        "9" = "September",
                        "10" = "October",
                        "11" = "November",
                        "12" = "December")) |>
  select(-waste_id, -test_date, -per_capita_sars_co_v_2_load_n1_copies_per_day_per_population, -population_served_estimated, -wwtp_name)

nyc_wwtp
```

Sub dataset
```{r}
rtqpcr <-
  nyc_wwtp |>
  filter(year %in% c(2021, 2022), technology == "RT-qPCR") |>
  select(-lat_wwtp, -lon_wwtp, -annotation)

dpcr <-
  nyc_wwtp |>
  filter(year %in% c(2021, 2022), technology == "dPCR") |>
  select(-lat_wwtp, -lon_wwtp, -annotation)
```
dpcr is not large enough to do data analysis.

data analysis
```{r}
trend_plot <-
  rtqpcr |>
  filter(year == 2021) |>
  group_by(month, wrrf_abbreviation) |>
  summarise(ave_conc = mean(concentration)) |>
  ggplot(aes(x = month, y = ave_conc, color = wrrf_abbreviation, group = wrrf_abbreviation)) +
  geom_line(alpha = .5) +
  geom_point(alpha = .5)

trend_plot
```


















```{r}
nyc_wwtp |>
  filter(year == 2022, technology == "RT-qPCR") |>
  group_by(month, wrrf_abbreviation) |>
  ggplot(aes(x = month, y = concentration, color = wrrf_abbreviation)) +
  geom_point(alpha = .5)
```

```{r}
avg_concentration_2022 = 
  rtqpcr |> 
  filter(year == 2022) |>
  group_by(month, wrrf_abbreviation) |> 
  summarise(data_value_avg = mean(concentration))
```
```{r}
avg_concentration_2022 |> 
  ggplot(aes(x = month, y = data_value_avg, color = wrrf_abbreviation, group = wrrf_abbreviation)) + 
  geom_line(alpha = .5) +
  geom_point() + 
  labs(x = "Month", 
       y = "Average Covid-19 Concentration of each waste water facility", 
       title = "Average Covid-19 Concentration of each waste water facility in 2022 in New York State") + 
  theme(legend.position = "bottom",
        legend.box.background = element_rect())
```



```{r}
library(leaflet)
wwtp_map <-
  nyc_wwtp |>
  leaflet() |>
  addTiles() |>
  addMarkers(
    ~lon_wwtp, ~lat_wwtp
  )

wwtp_map
```
14 wwtps map


##Questions
1 The concentration of covid for each station on average
2 literature review foe two diff tech (RT-qPCR, dPCR)
3 Year 2021 and 2022


