---
title: "Proposal"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**The group members (names and UNIs)**

Wendy Zhou (wz2630), Jianing Liu (jl6325), Ye Yuan (yy3295), Beicheng Huang (bh2852), Zhiqi Liu (al4327)

**The tentative project title**

Assessing SARS-CoV-2 Concentrations in NYC Wastewater

**The motivation for this project**

COVID-19 cases are constantly fluctuating and to better understand recent trends, we decided to analyze SARS-CoV-2 concentrations in wastewater data for the possibility of future public health interventions.

**The intended final products**

Webpage with project report, data processing, interactive map, statistical analyses, and screencast pages.
project report: goals/purposes
data processing: data sources and methods
analyses: showing associations / trends 

**The anticipated data sources**

* SARS-CoV-2 concentrations measured in NYC Wastewater (NYC Open Data)

* DOHMH COVID-19 Antibody-by-Borough (NYC Open Data)

**The planned analyses / visualizations / coding challenges**

* map of SARS-CoV-2 wastewater concentrations in NYC
* map of COVID-19 Antibody by Borough in NYC
* Correlation visualizations
* ANOVA Test

**The planned timeline**

* Meet every Tuesday and Thursday after class, 11:30am - 12:30pm

* Nov 13 - Nov 19 Data collection and cleaning

* Nov 20 - Nov 26 Data analysis and visualizations

* Nov 27 - Dec 03 Working on webpage

* Dec 04 - Dec 10 Finalizing webpage, writing report, preparing in-class discussion

